#!/bin/sh
#
# Extremely crude util for creating forum directories.

BBSDIR=/usr/bbs
FILEDIR=$BBSDIR/save/messages

cd $FILEDIR
rm -rf *

echo Forum directories will be created in $FILEDIR

echo -n Making forums
for i in 1 2 3 4 5 6 7 8 9; do
    echo -n " $i"
    FORUM=forum.$i
    mkdir $FORUM
done

for i in 1 2 3 4 5 6 7 8 9; do
    for j in 0 1 2 3 4 5 6 7 8 9; do
        echo -n " $i$j"
        FORUM=forum.$i$j
        mkdir $FORUM
    done
done

for i in 0 1 2 3 4; do
    for j in 0 1 2 3 4 5 6 7 8 9; do
        FORUM=forum.1$i$j
        echo -n " 1$i$j"
        mkdir $FORUM
    done
done
echo
echo Making Lobby...
mkdir forum.0
chown bbs.bbs . -R
chmod go-rwx . -R
echo "Your BBS now has 150 forums."
cd -
