#!/bin/sh
#
# $Id$
#
# Creates BBS banner with BBS software version, MySQL version and number of
# compiles. (hopefully) Should still be modified to run from `make' rather
# than from `./configure'.
# Also, this should trap ctrl-c and whatnot and create the version regardless
# of being interrupted.

# Check for .version file.
# If exists, read in, add one and save. If doesn't exist, set version to 1
# and create the file for next time.
#
if [ -f .version ]; then
    echo "updating include/version.h"
    typeset -i bbs_version=`/bin/cat .version`
    bbs_version=$bbs_version+1
else
    echo "creating include/version.h"
    typeset -i bbs_version=1
fi

# Save new version number back into file.
#
echo $bbs_version > .version

# Nasty call to MySQL which is prolly absolutely not cross-platform to
# get the MySQL version. (If it is installed)
#
MYSQL=x`which mysql`
if [ $MYSQL = x ]; then 
     echo -e "#define BBS_VERSION\t\"Mono 2.061 (#$bbs_version) - `uname -m` `uname -s` `uname -r`\"" > include/version.h
else
    MYSQL="`which mysql` --version"
    SQLVERSION="MySQL `$MYSQL | awk '{print $5}' | awk -F',' '{print $1}'`"
     echo -e "#define BBS_VERSION\t\"Mono 2.061 (#$bbs_version) - `uname -m` `uname -s` `uname -r` - $SQLVERSION\"" > include/version.h
fi

# And we're all done.
