# initialises the country table with ISO 3166 data
# get updates here: http://www.din.de/gremien/nas/nabd/iso3166ma/index.html 
delete from country;
insert into country(code,englishname) values('AD','Andorra');
insert into country(code,englishname) values('AE','United Arab Emirates');
insert into country(code,englishname) values('AF','Afghanistan');
insert into country(code,englishname) values('AG','Antigua & Barbuda');
insert into country(code,englishname) values('AI','Anguilla');
insert into country(code,englishname) values('AL','Albania');
insert into country(code,englishname) values('AM','Armenia');
insert into country(code,englishname) values('AN','Netherlands Antilles');
insert into country(code,englishname) values('AO','Angola');
insert into country(code,englishname) values('AQ','Antarctica');
insert into country(code,englishname) values('AR','Argentina');
insert into country(code,englishname) values('AS','Samoa (American)');
insert into country(code,englishname) values('AT','Austria');
insert into country(code,englishname) values('AU','Australia');
insert into country(code,englishname) values('AW','Aruba');
insert into country(code,englishname) values('AZ','Azerbaijan');
insert into country(code,englishname) values('BA','Bosnia & Herzegovina');
insert into country(code,englishname) values('BB','Barbados');
insert into country(code,englishname) values('BD','Bangladesh');
insert into country(code,englishname) values('BE','Belgium');
insert into country(code,englishname) values('BF','Burkina Faso');
insert into country(code,englishname) values('BG','Bulgaria');
insert into country(code,englishname) values('BH','Bahrain');
insert into country(code,englishname) values('BI','Burundi');
insert into country(code,englishname) values('BJ','Benin');
insert into country(code,englishname) values('BM','Bermuda');
insert into country(code,englishname) values('BN','Brunei');
insert into country(code,englishname) values('BO','Bolivia');
insert into country(code,englishname) values('BR','Brazil');
insert into country(code,englishname) values('BS','Bahamas');
insert into country(code,englishname) values('BT','Bhutan');
insert into country(code,englishname) values('BV','Bouvet Island');
insert into country(code,englishname) values('BW','Botswana');
insert into country(code,englishname) values('BY','Belarus');
insert into country(code,englishname) values('BZ','Belize');
insert into country(code,englishname) values('CA','Canada');
insert into country(code,englishname) values('CC','Cocos (Keeling) Islands');
insert into country(code,englishname) values('CD','Congo (Dem. Rep.)');
insert into country(code,englishname) values('CF','Central African Rep.');
insert into country(code,englishname) values('CG','Congo (Rep.)');
insert into country(code,englishname) values('CH','Switzerland');
insert into country(code,englishname) values('CI','Cote d\'Ivoire');
insert into country(code,englishname) values('CK','Cook Islands');
insert into country(code,englishname) values('CL','Chile');
insert into country(code,englishname) values('CM','Cameroon');
insert into country(code,englishname) values('CN','China');
insert into country(code,englishname) values('CO','Colombia');
insert into country(code,englishname) values('CR','Costa Rica');
insert into country(code,englishname) values('CU','Cuba');
insert into country(code,englishname) values('CV','Cape Verde');
insert into country(code,englishname) values('CX','Christmas Island');
insert into country(code,englishname) values('CY','Cyprus');
insert into country(code,englishname) values('CZ','Czech Republic');
insert into country(code,englishname) values('DE','Germany');
insert into country(code,englishname) values('DJ','Djibouti');
insert into country(code,englishname) values('DK','Denmark');
insert into country(code,englishname) values('DM','Dominica');
insert into country(code,englishname) values('DO','Dominican Republic');
insert into country(code,englishname) values('DZ','Algeria');
insert into country(code,englishname) values('EC','Ecuador');
insert into country(code,englishname) values('EE','Estonia');
insert into country(code,englishname) values('EG','Egypt');
insert into country(code,englishname) values('EH','Western Sahara');
insert into country(code,englishname) values('ER','Eritrea');
insert into country(code,englishname) values('ES','Spain');
insert into country(code,englishname) values('ET','Ethiopia');
insert into country(code,englishname) values('FI','Finland');
insert into country(code,englishname) values('FJ','Fiji');
insert into country(code,englishname) values('FK','Falkland Islands');
insert into country(code,englishname) values('FM','Micronesia');
insert into country(code,englishname) values('FO','Faeroe Islands');
insert into country(code,englishname) values('FR','France');
insert into country(code,englishname) values('FX','France, Metropolitan');
insert into country(code,englishname) values('GA','Gabon');
insert into country(code,englishname) values('GB','Britain (UK)');
insert into country(code,englishname) values('GD','Grenada');
insert into country(code,englishname) values('GE','Georgia');
insert into country(code,englishname) values('GF','French Guiana');
insert into country(code,englishname) values('GH','Ghana');
insert into country(code,englishname) values('GI','Gibraltar');
insert into country(code,englishname) values('GL','Greenland');
insert into country(code,englishname) values('GM','Gambia');
insert into country(code,englishname) values('GN','Guinea');
insert into country(code,englishname) values('GP','Guadeloupe');
insert into country(code,englishname) values('GQ','Equatorial Guinea');
insert into country(code,englishname) values('GR','Greece');
insert into country(code,englishname) values('GS','South Georgia & the South Sandwich Islands');
insert into country(code,englishname) values('GT','Guatemala');
insert into country(code,englishname) values('GU','Guam');
insert into country(code,englishname) values('GW','Guinea-Bissau');
insert into country(code,englishname) values('GY','Guyana');
insert into country(code,englishname) values('HM','Heard Island & McDonald Islands');
insert into country(code,englishname) values('HN','Honduras');
insert into country(code,englishname) values('HR','Croatia');
insert into country(code,englishname) values('HT','Haiti');
insert into country(code,englishname) values('HU','Hungary');
insert into country(code,englishname) values('ID','Indonesia');
insert into country(code,englishname) values('IE','Ireland');
insert into country(code,englishname) values('IL','Israel');
insert into country(code,englishname) values('IN','India');
insert into country(code,englishname) values('IO','British Indian Ocean Territory');
insert into country(code,englishname) values('IQ','Iraq');
insert into country(code,englishname) values('IR','Iran');
insert into country(code,englishname) values('IS','Iceland');
insert into country(code,englishname) values('IT','Italy');
insert into country(code,englishname) values('JM','Jamaica');
insert into country(code,englishname) values('JO','Jordan');
insert into country(code,englishname) values('JP','Japan');
insert into country(code,englishname) values('KE','Kenya');
insert into country(code,englishname) values('KG','Kirgizstan');
insert into country(code,englishname) values('KH','Cambodia');
insert into country(code,englishname) values('KI','Kiribati');
insert into country(code,englishname) values('KM','Comoros');
insert into country(code,englishname) values('KN','St Kitts & Nevis');
insert into country(code,englishname) values('KP','Korea (North)');
insert into country(code,englishname) values('KR','Korea (South)');
insert into country(code,englishname) values('KW','Kuwait');
insert into country(code,englishname) values('KY','Cayman Islands');
insert into country(code,englishname) values('KZ','Kazakhstan');
insert into country(code,englishname) values('LA','Laos');
insert into country(code,englishname) values('LB','Lebanon');
insert into country(code,englishname) values('LC','St Lucia');
insert into country(code,englishname) values('LI','Liechtenstein');
insert into country(code,englishname) values('LK','Sri Lanka');
insert into country(code,englishname) values('LR','Liberia');
insert into country(code,englishname) values('LS','Lesotho');
insert into country(code,englishname) values('LT','Lithuania');
insert into country(code,englishname) values('LU','Luxembourg');
insert into country(code,englishname) values('LV','Latvia');
insert into country(code,englishname) values('LY','Libya');
insert into country(code,englishname) values('MA','Morocco');
insert into country(code,englishname) values('MC','Monaco');
insert into country(code,englishname) values('MD','Moldova');
insert into country(code,englishname) values('MG','Madagascar');
insert into country(code,englishname) values('MH','Marshall Islands');
insert into country(code,englishname) values('MK','Macedonia');
insert into country(code,englishname) values('ML','Mali');
insert into country(code,englishname) values('MM','Myanmar (Burma)');
insert into country(code,englishname) values('MN','Mongolia');
insert into country(code,englishname) values('MO','Macao');
insert into country(code,englishname) values('MP','Northern Mariana Islands');
insert into country(code,englishname) values('MQ','Martinique');
insert into country(code,englishname) values('MR','Mauritania');
insert into country(code,englishname) values('MS','Montserrat');
insert into country(code,englishname) values('MT','Malta');
insert into country(code,englishname) values('MU','Mauritius');
insert into country(code,englishname) values('MV','Maldives');
insert into country(code,englishname) values('MW','Malawi');
insert into country(code,englishname) values('MX','Mexico');
insert into country(code,englishname) values('MY','Malaysia');
insert into country(code,englishname) values('MZ','Mozambique');
insert into country(code,englishname) values('NA','Namibia');
insert into country(code,englishname) values('NC','New Caledonia');
insert into country(code,englishname) values('NE','Niger');
insert into country(code,englishname) values('NF','Norfolk Island');
insert into country(code,englishname) values('NG','Nigeria');
insert into country(code,englishname) values('NI','Nicaragua');
insert into country(code,englishname) values('NL','Netherlands');
insert into country(code,englishname) values('NO','Norway');
insert into country(code,englishname) values('NP','Nepal');
insert into country(code,englishname) values('NR','Nauru');
insert into country(code,englishname) values('NU','Niue');
insert into country(code,englishname) values('NZ','New Zealand');
insert into country(code,englishname) values('OM','Oman');
insert into country(code,englishname) values('PA','Panama');
insert into country(code,englishname) values('PE','Peru');
insert into country(code,englishname) values('PF','French Polynesia');
insert into country(code,englishname) values('PG','Papua New Guinea');
insert into country(code,englishname) values('PH','Philippines');
insert into country(code,englishname) values('PK','Pakistan');
insert into country(code,englishname) values('PL','Poland');
insert into country(code,englishname) values('PM','St Pierre & Miquelon');
insert into country(code,englishname) values('PN','Pitcairn');
insert into country(code,englishname) values('PR','Puerto Rico');
insert into country(code,englishname) values('PS','Palestine');
insert into country(code,englishname) values('PT','Portugal');
insert into country(code,englishname) values('PW','Palau');
insert into country(code,englishname) values('PY','Paraguay');
insert into country(code,englishname) values('QA','Qatar');
insert into country(code,englishname) values('RE','Reunion');
insert into country(code,englishname) values('RO','Romania');
insert into country(code,englishname) values('RU','Russia');
insert into country(code,englishname) values('RW','Rwanda');
insert into country(code,englishname) values('SA','Saudi Arabia');
insert into country(code,englishname) values('SB','Solomon Islands');
insert into country(code,englishname) values('SC','Seychelles');
insert into country(code,englishname) values('SD','Sudan');
insert into country(code,englishname) values('SE','Sweden');
insert into country(code,englishname) values('SG','Singapore');
insert into country(code,englishname) values('SH','St Helena');
insert into country(code,englishname) values('SI','Slovenia');
insert into country(code,englishname) values('SJ','Svalbard & Jan Mayen');
insert into country(code,englishname) values('SK','Slovakia');
insert into country(code,englishname) values('SL','Sierra Leone');
insert into country(code,englishname) values('SM','San Marino');
insert into country(code,englishname) values('SN','Senegal');
insert into country(code,englishname) values('SO','Somalia');
insert into country(code,englishname) values('SR','Suriname');
insert into country(code,englishname) values('ST','Sao Tome & Principe');
insert into country(code,englishname) values('SV','El Salvador');
insert into country(code,englishname) values('SY','Syria');
insert into country(code,englishname) values('SZ','Swaziland');
insert into country(code,englishname) values('TC','Turks & Caicos Is');
insert into country(code,englishname) values('TD','Chad');
insert into country(code,englishname) values('TF','French Southern & Antarctic Lands');
insert into country(code,englishname) values('TG','Togo');
insert into country(code,englishname) values('TH','Thailand');
insert into country(code,englishname) values('TJ','Tajikistan');
insert into country(code,englishname) values('TK','Tokelau');
insert into country(code,englishname) values('TM','Turkmenistan');
insert into country(code,englishname) values('TN','Tunisia');
insert into country(code,englishname) values('TO','Tonga');
insert into country(code,englishname) values('TP','East Timor');
insert into country(code,englishname) values('TR','Turkey');
insert into country(code,englishname) values('TT','Trinidad & Tobago');
insert into country(code,englishname) values('TV','Tuvalu');
insert into country(code,englishname) values('TW','Taiwan');
insert into country(code,englishname) values('TZ','Tanzania');
insert into country(code,englishname) values('UA','Ukraine');
insert into country(code,englishname) values('UG','Uganda');
insert into country(code,englishname) values('UM','US minor outlying islands');
insert into country(code,englishname) values('US','United States');
insert into country(code,englishname) values('UY','Uruguay');
insert into country(code,englishname) values('UZ','Uzbekistan');
insert into country(code,englishname) values('VA','Vatican City');
insert into country(code,englishname) values('VC','St Vincent');
insert into country(code,englishname) values('VE','Venezuela');
insert into country(code,englishname) values('VG','Virgin Islands (UK)');
insert into country(code,englishname) values('VI','Virgin Islands (US)');
insert into country(code,englishname) values('VN','Vietnam');
insert into country(code,englishname) values('VU','Vanuatu');
insert into country(code,englishname) values('WF','Wallis & Futuna');
insert into country(code,englishname) values('WS','Samoa (Western)');
insert into country(code,englishname) values('YE','Yemen');
insert into country(code,englishname) values('YT','Mayotte');
insert into country(code,englishname) values('YU','Yugoslavia');
insert into country(code,englishname) values('ZA','South Africa');
insert into country(code,englishname) values('ZM','Zambia');
insert into country(code,englishname) values('ZW','Zimbabwe');
