<?

 /*
  * $Id$
  */

function profile_user($username, $victim) {

    // Check user priv.
    //
    switch (check_priv($username, 0)) {
        case -1 :
		errorimage("You are not currently logged in. Log in first!");
	        return;
                break;
	default:
	    break;
    }

    connect_db();

    $victim = urldecode($victim);

    // Instantiate new user_t.
    //
    $user = new user_t;

    if( ($user->init($victim)) == false )
        errorimage("I have no idea who $victim is!");
    else
        $user->show_profile();
}

?>
