/* data arrays */
/*

char *goto[] = {
    "No unread messages.",
    "No unread spacefood sticks.",
    "We killed the gotos!",
    "Pink elephants, aaaaahhhhh!",
    "Very funny, Scotty. Now beam down my pants.",
    "What did you go and do that for?",
    "Oh no! It's bicyclerepairpersonman! We're doomed!",
    "There's one! Shoot it!",
    "Ceci n'est pas un moniteur.",
    "Cthulhu ftagh'n!",
    "I need more random gotos!",
    "Today the fridge, tomorrow the world!",
    "Gotta hate when no one posts.",
    "Have you ever thought about posting?",
    "I am the terror that flaps in the night!",
    "Vodka Martini, shaken, not stirred.",
    "You, me, the keyboard. Whaddaya say? ;)",
    "A pickle or two cows. Which would you prefer?",
    "It's a small world after all.",
    "Ooooooh La La!",
    "Connection opened by foreign host.",
    "I like nachos!",
    "His name was Boggy B.",
    "If you don't care where you are, you ain't lost.",
    "No undead messages.",
    "May the Schwartz be with you!",
    "Oh, the BBS! It, it, it's so BIG!",
    "Regular price, four bucks, four bucks, four bucks.",
    "Shouldn't your keyboard use protection?",
    "Do you ever get that unfresh feeling?",
    "Oh Yes! Yes! Punch that spacebar!",
    "My bologna has a first name.",
    "My name is Bill Gates. Nice to meet you.",
    "No unread sausages.",
    "Eat the squeaky toy!",
    "I get by with a little help from my friends.",
    "Type\1w: <\1rs\1w> <\1rj\1w> <\1r21\1w> <\1re\1w>",
    "I've got a luvvverly bunch of coconuts...",
    "You don't know the power of the dark side.",
    "We come in peace, shoot to kill.",
    "Dammit Jim, I'm a computer, not a punchbag!",
    "John ketley is a weather man...",
    "I like to blow up lizards!",
    "And I like to burn stuff!",
    "The government says you must!",
    "Having a bad-hair-day, are we?",
    "What would happen if I touched this bu",
    "http://www.spektragraphics.com/~kam/clients/",
    "No unfed messages.",
    "Condoms needed!",
    "I want my $2!",
    "I want, I want to see a post.",
    "What do you want from me?",
    "Life's a grapefruit, I want my money back.",
    "Vodka Martijn, shaken, not stirred.",
    "No unreal messages.",
                if( EQ( usersupp->username, "Tisara" ) )
                    cprintf( "Become one with that spacebar dudette!",
                else
    	        cprintf( "Become one with that spacebar buddy!",
    "Just because you know that doesn't make you a genius.",
    "Try a little more hrmph next time.",
    "Niks.",
    "Like... oh wow.. ya know?",
    "Ignore me while I drink.",
    "Soup. Mushroom soup.",
    "No unread marsares.",
    "Happy new year!",
    "Quick, hand me the pencils!",
    "No inbred messages.",
    "No misled messages.",
    "Quick!  Nobody post.",
    "Bork! Bork! Bork!",
    "Thongs! Get yer thongs here mate!",
    "Urr, you too?",
    "No! I can't take it anymore, HELP!",
    "Llamas are bigger than frogs.",
    "This is a clue. They did it. *points*",
    "Once upon a time in a galaxy far, far away...",
    "Lick me, I'm made of chocolate.",
    "Elementary, my dear Watson.",
    "No shit, Sherlock!",
    "Jooooooohan! Elf uur!",
    "Please fill out your registration card now.",
    "You've got a luvvverly bunch of coconuts...",
    "Womble! Womble! Womble!",
    "Please secure your tray tables.",
    "Mouse, my kingdom for a mouse!",
    "!toof eht pihsrow llA",
    "\1pU\1yn\1rr\1be\1wa\1gd\1ca\1pb\1gl\1be \1rc\1po\1wl\1yo\1cu\1rr\1gf\1pu\1bl \1yt\1re\1wx\1pt\1c.",
    "There is an antelope eating on the croquethoops.",
    "Nine! Nine! Nine! Err, seven?",
    "I live in Karachi, are you a carrot?",
    "Take us to your leader!!!",
    "No unread massages.",
    "No unsaid messages.",
    "I didn't recognize you without the handcuffs.",
    "Pride is all very well, but a sausage is a sausage.",
    "Woof bloody woof.",
    "Woof. In tones of low menace.",
    "Go ahead, bake my quiche",
    "In the Beginning there was nothing, which exploded.",
    "++?????++ Out of Cheese Error. Redo From Start.",
    "A screwdriver too few perhaps?",
    "There's a kangaroo loose in the top paddock.",
    "It's a sandwhich short of a picnic, I'm afraid.",
    "No unread messiahs.",
    "Fruitbowls are for queens of deep space.",
    "Oh look, there's Carmen! Now where's that fruitbowl?",
    "Lucky Phil was a dutchman, betcha never knew that did ya?",
    "If ya drink then drive you're a bloody idiot.",
    "No unread rivers.",
    "Some unread heads?",
    "J0hann! Elve ar!",
    "The armadillo fits into only four lines!",
    "I think I know why the surpositories taste so bad, doctor.",
    "You will go blind that way.",
    "Touch that space bar one more time and I will have to spank you!",
    "Sex?  No thank you, I'm on a diet.",
    "Quickly type \1w<\1rl\1w><\1ry\1w>\1g to take the quiz of the day.",
    "Help! Help!  I'm being oppressed!",
    "KRACK-O-POP!",
    "Touch the screen! Touch the screen!"
};

char *heroname[] = {
	"Alien",
	"America",
	"Android",
	"Angel",
	"Ant",
	"Ape",
	"Armadillo",
	"Arrow",
	"Atom",
	"Avenger",
	"Baby",
	"Bat",
	"Beast",
	"Bee",
	"Beetle",
	"Bird",
	"Blade",
	"Blur",
	"Bolt",
	"Boy",
	"Brain",
	"Bug",
	"Bullet",
	"Canary",
	"Cavalier",
	"Centurion",
	"Chameleon",
	"Champion",
	"Chimp",
	"Claw",
	"Condor",
	"Dancer",
	"Dazzler",
	"Defender",
	"Demon",
	"Devil",
	"Dog",
	"Dragon",
	"Droid",
	"Duke",
	"Eagle",
	"Emperor",
	"Empress",
	"Enigma",
	"Eye",
	"Falcon",
	"Fang",
	"Finger",
	"Flame",
	"Flash",
	"Flea",
	"Flower",
	"Fly",
	"Fox",
	"Freak",
	"Frog",
	"Fury",
	"F|ghter",
	"F|re",
	"Gal",
	"Ghost",
	"Girl",
	"Glory",
	"Gol|ath",
	"Gorilla",
	"Guardian",
	"Guy",
	"G|ant",
	"Hammer",
	"Hawk",
	"Hornet",
	"Inferno",
	"Jack",
	"Jet",
	"Kid",
	"King",
	"Kn|ght",
	"Lad",
	"Lady",
	"Lantern",
	"Lass",
	"Lord",
	"L|ght",
	"L|ghtning",
	"L|on",
	"Man",
	"Mane",
	"Manhunter",
	"Mariner",
	"Marvel",
	"Mask",
	"Master",
	"Mistress",
	"Mouse",
	"Ninja",
	"Nova",
	"Panther",
	"Phantom",
	"Platypus",
	"Prince",
	"Princess",
	"Protector",
	"Prowler",
	"Punisher",
	"Queen",
	"Racer",
	"Racoon",
	"Ranger",
	"Rat",
	"Robot",
	"Rocket",
	"R|der",
	"Samurai",
	"Shadow",
	"Shield",
	"Shrike",
	"Singer",
	"Skier",
	"Slayer",
	"Soarer",
	"Sorcerer",
	"Sorceress",
	"Spear",
	"Specter",
	"Sp|der",
	"Squid",
	"Squirrel",
	"Stalker",
	"Star",
	"Storm",
	"Surfer",
	"Sword",
	"S|dekick",
	"Torpedo",
	"T|ger",
	"T|tan",
	"Victory",
	"Viking",
	"Vision",
	"Walker",
	"Warlock",
	"Warrior",
	"Wave",
	"Wing",
	"Witch",
	"Wizard",
	"Wolf",
	"Woman",
	"Wombat",
	"Wonder",
	"Worm",
	"X",
	"Yak"
};
char *herotitle[] = {
	"Air ",
	"Alien ",
	"Alpha ",
	"Ambush ",
	"Android ",
	"Animal ",
	"Ant ",
	"Aqua-",
	"Arch-",
	"Armadillo ",
	"Astro-",
	"Atomic ",
	"Azure ",
	"B'Wana ",
	"Bat ",
	"Bee ",
	"Beta ",
	"Bionic ",
	"Black ",
	"Blood ",
	"Blue ",
	"Bronze ",
	"Bullet ",
	"Caped ",
	"Captain ",
	"Cat ",
	"Chameleon ",
	"Commander ",
	"Commodore ",
	"Composite ",
	"Compu-",
	"Copper ",
	"Cosmic ",
	"Crimson ",
	"Cyber-",
	"Dare-",
	"Dark ",
	"Dawn ",
	"Death ",
	"Delta ",
	"Detective ",
	"Doc ",
	"Doctor ",
	"Dog ",
	"Dragon ",
	"Dream ",
	"Duke ",
	"Dynamo ",
	"Earth ",
	"Elasti-",
	"Element ",
	"Emerald ",
	"Fly ",
	"Flying ",
	"Frog ",
	"Future ",
	"F|ghting ",
	"F|re ",
	"Gamma ",
	"Gaseous ",
	"General ",
	"Ghost ",
	"Gold ",
	"Golden ",
	"Gorilla ",
	"Green ",
	"Grey ",
	"G|ant ",
	"Hawk ",
	"Human ",
	"Hyper-",
	"Ice ",
	"Insect ",
	"Invisible ",
	"Iron ",
	"Jade ",
	"Karate ",
	"Laser ",
	"Lieutenant ",
	"Living ",
	"L|ght ",
	"L|ghtning ",
	"L|on ",
	"Machine ",
	"Mad ",
	"Magna-",
	"Magnetic ",
	"Major ",
	"Martian ",
	"Masked ",
	"Mighty ",
	"Miss ",
	"Mister ",
	"Moon ",
	"M|cro-",
	"M|nd ",
	"N|ght ",
	"Omega ",
	"Orange ",
	"Phantom ",
	"Platinum ",
	"Platypus ",
	"Power ",
	"Prince ",
	"Princess ",
	"Professor ",
	"Purple ",
	"Racoon ",
	"Rainbow ",
	"Rat ",
	"Red ",
	"Ring ",
	"Robot ",
	"Rocket ",
	"Ruby ",
	"Samurai ",
	"Sand ",
	"Scarlet ",
	"Screaming ",
	"Sea ",
	"Seagoing ",
	"Secret ",
	"Sergeant ",
	"Shadow ",
	"Shatter ",
	"She-",
	"Shrinking ",
	"Sh|ning ",
	"Silver ",
	"Sky ",
	"Snow ",
	"Space ",
	"Speed ",
	"Sp|der ",
	"Squirrel ",
	"Star ",
	"Steel ",
	"Sub-",
	"Suic|de ",
	"Sun ",
	"Super ",
	"Techni-",
	"Terra-",
	"Thunder ",
	"Tomorrow ",
	"T|me ",
	"Ultra ",
	"Valiant ",
	"V|olet ",
	"Warrior ",
	"Water ",
	"Wh|te ",
	"Wind ",
	"Wing ",
	"Winged ",
	"Winter ",
	"Wolf ",
	"Wombat ",
	"Wonder ",
	"X-",
	"Yak ",
	"Yellow "
};
char *heroadjective[] = {
	"$6 million", "adjectiveless", "amazing", "astonishing",
	"astounding", "athletic", "bewildering", "bizarre",
	"courteous", "dazzling", "electrifying", "enigmatic",
	"ever-loving, blue-eyed", "famous", "fantastic", "fearless",
	"friendly, neighborhood", "grim 'n' gritty", "impossible",
	"incredible", "indescribable", "intangible", "invincible",
	"invulnerable", "irresistable", "kool", "marvelous", "mighty",
	"morphin'", "noble", "perplexing", "polite", "savage",
	"sensational", "spectacular", "spellbinding", "strange",
	"stupendous", "super-intelligent", "unbeatable", "uncanny",
	"valiant", "valorous", "weird", "wonderous", "evil"
};
char *herovehicle[] = {
	"Bike", "Boat", "Broom", "Buggy", "Car", "Chariot", "Cycle",
	"Dragon", "Glider", "Horse", "Hovercraft", "Hydrofoil", "Jet",
	"Plane", "Pogo Stick", "Rocket", "Rollerblades", "Saucer",
	"Ship", "Shuttle", "Skates", "Skis", "Sled", "Starship",
	"Stilts", "Submarine", "Surfboard", "Van", "Wings"
};
char *herotype[] = {
	"Admantium", "Air", "Anti-matter", "Cosmic", "Energy", "Ether",
	"Flash", "Foam", "Force", "Glue", "Gravity", "Laser", "Light",
	"Magic", "Magnetic", "Mystic", "Radiation", "Sonic", "Star",
	"Stellar", "Strobe", "Trick", "Vibranium", "Web"
};
char *heroweapon[] = {
	"Armor", "Arrows", "Battleaxe", "Blaster", "Boomerang", "Bow",
	"Bullets", "Cannon", "Chain", "Claws", "Crossbow", "Dagger",
	"Discs", "Gun", "Hammer", "Knife", "Lance", "Lasso", "Needles",
	"Neutralizer", "Nunchucks", "Pistol", "Rod", "Sai", "Shield",
	"Shooter", "Shotgun", "Spear", "Staff", "Sword", "Thorns",
	"Throwing Stars"
};
char *heropower[] = {
	"Chemical", "Chronal", "Cybernetics", "Extra-dimensional",
	"Extra-terrestrial", "Gadgets", "Magical", "Meditation",
	"Metahuman", "Mutagen", "Mutant", "Mystical", "Mythical God(ess)",
	"None", "Paranormal", "Psychic", "Radiation", "Solar", "Spinach",
	"Super-goobers", "Supernatural", "Technological", "Training",
	"Unknown", "Quaaludes"
};
*/

/* defines */

#define NAMNUM	153
#define TITNUM	162
#define ADJNUM	46
#define VEHNUM	29
#define TYPNUM	24
#define WEANUM	32
#define	POWNUM	25
#define GOTOS	123

/* prototypes */

extern void random_goto ( void );
extern int roulette ( void );
extern void crap( int, const char *, int );
extern void generate_hero( void );
extern void roll_the_bones( void );
/* eof */
