/* $Id$ */

/*
 * Contains data & defines for the superhero generator.
 */

extern void generate_hero( void );

#define NAMNUM  153
#define TITNUM  162
#define ADJNUM  46
#define VEHNUM  29
#define TYPNUM  24
#define WEANUM  32
#define POWNUM  25
#define GOTOS   123

char *heroname[] =
{
    "Alien",
    "America",
    "Android",
    "Angel",
    "Ant",
    "Ape",
    "Armadillo",
    "Arrow",
    "Atom",
    "Avenger",
    "Baby",
    "Bat",
    "Beast",
    "Bee",
    "Beetle",
    "Bird",
    "Blade",
    "Blur",
    "Bolt",
    "Boy",
    "Brain",
    "Bug",
    "Bullet",
    "Canary",
    "Cavalier",
    "Centurion",
    "Chameleon",
    "Champion",
    "Chimp",
    "Claw",
    "Condor",
    "Dancer",
    "Dazzler",
    "Defender",
    "Demon",
    "Devil",
    "Dog",
    "Dragon",
    "Droid",
    "Duke",
    "Eagle",
    "Emperor",
    "Empress",
    "Enigma",
    "Eye",
    "Falcon",
    "Fang",
    "Finger",
    "Flame",
    "Flash",
    "Flea",
    "Flower",
    "Fly",
    "Fox",
    "Freak",
    "Frog",
    "Fury",
    "F|ghter",
    "F|re",
    "Gal",
    "Ghost",
    "Girl",
    "Glory",
    "Gol|ath",
    "Gorilla",
    "Guardian",
    "Guy",
    "G|ant",
    "Hammer",
    "Hawk",
    "Hornet",
    "Inferno",
    "Jack",
    "Jet",
    "Kid",
    "King",
    "Kn|ght",
    "Lad",
    "Lady",
    "Lantern",
    "Lass",
    "Lord",
    "L|ght",
    "L|ghtning",
    "L|on",
    "Man",
    "Mane",
    "Manhunter",
    "Mariner",
    "Marvel",
    "Mask",
    "Master",
    "Mistress",
    "Mouse",
    "Ninja",
    "Nova",
    "Panther",
    "Phantom",
    "Platypus",
    "Prince",
    "Princess",
    "Protector",
    "Prowler",
    "Punisher",
    "Queen",
    "Racer",
    "Racoon",
    "Ranger",
    "Rat",
    "Robot",
    "Rocket",
    "R|der",
    "Samurai",
    "Shadow",
    "Shield",
    "Shrike",
    "Singer",
    "Skier",
    "Slayer",
    "Soarer",
    "Sorcerer",
    "Sorceress",
    "Spear",
    "Specter",
    "Sp|der",
    "Squid",
    "Squirrel",
    "Stalker",
    "Star",
    "Storm",
    "Surfer",
    "Sword",
    "S|dekick",
    "Torpedo",
    "T|ger",
    "T|tan",
    "Victory",
    "Viking",
    "Vision",
    "Walker",
    "Warlock",
    "Warrior",
    "Wave",
    "Wing",
    "Witch",
    "Wizard",
    "Wolf",
    "Woman",
    "Wombat",
    "Wonder",
    "Worm",
    "X",
    "Yak"
};
char *herotitle[] =
{
    "Air ",
    "Alien ",
    "Alpha ",
    "Ambush ",
    "Android ",
    "Animal ",
    "Ant ",
    "Aqua-",
    "Arch-",
    "Armadillo ",
    "Astro-",
    "Atomic ",
    "Azure ",
    "B'Wana ",
    "Bat ",
    "Bee ",
    "Beta ",
    "Bionic ",
    "Black ",
    "Blood ",
    "Blue ",
    "Bronze ",
    "Bullet ",
    "Caped ",
    "Captain ",
    "Cat ",
    "Chameleon ",
    "Commander ",
    "Commodore ",
    "Composite ",
    "Compu-",
    "Copper ",
    "Cosmic ",
    "Crimson ",
    "Cyber-",
    "Dare-",
    "Dark ",
    "Dawn ",
    "Death ",
    "Delta ",
    "Detective ",
    "Doc ",
    "Doctor ",
    "Dog ",
    "Dragon ",
    "Dream ",
    "Duke ",
    "Dynamo ",
    "Earth ",
    "Elasti-",
    "Element ",
    "Emerald ",
    "Fly ",
    "Flying ",
    "Frog ",
    "Future ",
    "F|ghting ",
    "F|re ",
    "Gamma ",
    "Gaseous ",
    "General ",
    "Ghost ",
    "Gold ",
    "Golden ",
    "Gorilla ",
    "Green ",
    "Grey ",
    "G|ant ",
    "Hawk ",
    "Human ",
    "Hyper-",
    "Ice ",
    "Insect ",
    "Invisible ",
    "Iron ",
    "Jade ",
    "Karate ",
    "Laser ",
    "Lieutenant ",
    "Living ",
    "L|ght ",
    "L|ghtning ",
    "L|on ",
    "Machine ",
    "Mad ",
    "Magna-",
    "Magnetic ",
    "Major ",
    "Martian ",
    "Masked ",
    "Mighty ",
    "Miss ",
    "Mister ",
    "Moon ",
    "M|cro-",
    "M|nd ",
    "N|ght ",
    "Omega ",
    "Orange ",
    "Phantom ",
    "Platinum ",
    "Platypus ",
    "Power ",
    "Prince ",
    "Princess ",
    "Professor ",
    "Purple ",
    "Racoon ",
    "Rainbow ",
    "Rat ",
    "Red ",
    "Ring ",
    "Robot ",
    "Rocket ",
    "Ruby ",
    "Samurai ",
    "Sand ",
    "Scarlet ",
    "Screaming ",
    "Sea ",
    "Seagoing ",
    "Secret ",
    "Sergeant ",
    "Shadow ",
    "Shatter ",
    "She-",
    "Shrinking ",
    "Sh|ning ",
    "Silver ",
    "Sky ",
    "Snow ",
    "Space ",
    "Speed ",
    "Sp|der ",
    "Squirrel ",
    "Star ",
    "Steel ",
    "Sub-",
    "Suic|de ",
    "Sun ",
    "Super ",
    "Techni-",
    "Terra-",
    "Thunder ",
    "Tomorrow ",
    "T|me ",
    "Ultra ",
    "Valiant ",
    "V|olet ",
    "Warrior ",
    "Water ",
    "Wh|te ",
    "Wind ",
    "Wing ",
    "Winged ",
    "Winter ",
    "Wolf ",
    "Wombat ",
    "Wonder ",
    "X-",
    "Yak ",
    "Yellow "
};
char *heroadjective[] =
{
    "$6 million", "adjectiveless", "amazing", "astonishing",
    "astounding", "athletic", "bewildering", "bizarre",
    "courteous", "dazzling", "electrifying", "enigmatic",
    "ever-loving, blue-eyed", "famous", "fantastic", "fearless",
    "friendly, neighborhood", "grim 'n' gritty", "impossible",
    "incredible", "indescribable", "intangible", "invincible",
    "invulnerable", "irresistable", "kool", "marvelous", "mighty",
    "morphin'", "noble", "perplexing", "polite", "savage",
    "sensational", "spectacular", "spellbinding", "strange",
    "stupendous", "super-intelligent", "unbeatable", "uncanny",
    "valiant", "valorous", "weird", "wonderous", "evil"
};
char *herovehicle[] =
{
    "Bike", "Boat", "Broom", "Buggy", "Car", "Chariot", "Cycle",
    "Dragon", "Glider", "Horse", "Hovercraft", "Hydrofoil", "Jet",
    "Plane", "Pogo Stick", "Rocket", "Rollerblades", "Saucer",
    "Ship", "Shuttle", "Skates", "Skis", "Sled", "Starship",
    "Stilts", "Submarine", "Surfboard", "Van", "Wings"
};
char *herotype[] =
{
    "Admantium", "Air", "Anti-matter", "Cosmic", "Energy", "Ether",
    "Flash", "Foam", "Force", "Glue", "Gravity", "Laser", "Light",
    "Magic", "Magnetic", "Mystic", "Radiation", "Sonic", "Star",
    "Stellar", "Strobe", "Trick", "Vibranium", "Web"
};
char *heroweapon[] =
{
    "Armor", "Arrows", "Battleaxe", "Blaster", "Boomerang", "Bow",
    "Bullets", "Cannon", "Chain", "Claws", "Crossbow", "Dagger",
    "Discs", "Gun", "Hammer", "Knife", "Lance", "Lasso", "Needles",
    "Neutralizer", "Nunchucks", "Pistol", "Rod", "Sai", "Shield",
    "Shooter", "Shotgun", "Spear", "Staff", "Sword", "Thorns",
    "Throwing Stars"
};
char *heropower[] =
{
    "Chemical", "Chronal", "Cybernetics", "Extra-dimensional",
    "Extra-terrestrial", "Gadgets", "Magical", "Meditation",
    "Metahuman", "Mutagen", "Mutant", "Mystical", "Mythical God(ess)",
    "None", "Paranormal", "Psychic", "Radiation", "Solar", "Spinach",
    "Super-goobers", "Supernatural", "Technological", "Training",
    "Unknown", "Quaaludes"
};
