#!/bin/sh
CONFIGFILE=$FILE
DATE=`date`
FILE=setup.h.$USER
INCDIR=
RUNNER=$USER@`hostname`

clear
echo
echo "Welcome to the Mono Code BBS setup section."
echo "Copyright The Monolith Community 1997"
echo
echo "-----------------------------------------------------------------------"
echo "Here you can configure the look of the BBS, such as titles and names. The"
echo "default settings will give you a look like a mix of a standard YAWC and a"
echo "standard DOC BBS."
echo "-----------------------------------------------------------------------"
echo
echo "Press return to continue..."
read ans
case "$ans" in
    *)
    ;;
esac
clear
echo
echo "PART 1 - Name the BBS."
echo "-----------------------------------------------------------------------"
echo "First you have to choose a name for your BBS. Enter the full"
echo "name, for example 'Monolith BBS'."
echo "-----------------------------------------------------------------------"
echo
ans=""
echo -n "(REQUIRED!) Enter BBS name: "
read ans
case "$ans" in
  "")
    echo
    echo "You MUST enter a BBS name!"
    echo
    exit
  ;;
esac
BBSNAME=$ans
echo
echo "-----------------------------------------------------------------------"
echo "Okay, your users will see 'Welcome to $BBSNAME.' when they connect to"
echo "your BBS."
echo "-----------------------------------------------------------------------"
echo
echo "Press return to continue..."
read ans
case "$ans" in
    *)
    ;;
esac
clear
echo
echo "PART 2 - Choose names for standard components."
echo "-----------------------------------------------------------------------"
echo "You will also need names for things such as forums, messages, users and"
echo "admin. If you don't want the default, enter your choices here. The part"
echo "of the BBS that will use this name is listed bewteen brackets."
echo "-----------------------------------------------------------------------"
echo
echo "Press return to continue..."
read ans
case "$ans" in
    *)
    ;;
esac
### Configuring names...
echo
ans=Forum
echo -n "(forums)   Enter forum name [$ans]: "
read ans
case "$ans" in
  "")
    ans=Forum
  ;;
esac
FORUM=$ans
ans=message
echo -n "(forums)   Enter message name [$ans]: "
read ans
case "$ans" in
  "")
    ans=message
  ;;
esac
MESSAGE=$ans
ans=eXpress
echo -n "(express)  Enter a header for x messages [$ans]: "
read ans
case "$ans" in
  "")
    ans=eXpress
  ;;
esac
EXPRESS=$ans
ans=message
echo -n "(express)  Enter a name for $EXPRESS messages [$ans]: "
read ans
case "$ans" in
  "")
    ans=message
  ;;
esac
X_MESSAGE=$ans
ans=User
echo -n "(express)  Enter a name for users [$ans]: "
read ans
case "$ans" in
  "")
    ans=User
  ;;
esac
USER=$ans
ans=name
echo -n "(wholist)  Enter $USER-postfix for wholist [$ans]: "
read ans
case "$ans" in
  "")
    ans=name
  ;;
esac
USERNAME=$ans
ans=Doing
echo -n "(wholist)  Enter a name for the doing [$ans]: "
read ans
case "$ans" in
  "")
    ans=Doing
  ;;
esac
DOING=$ans
ans=Location
echo -n "(wholist)  Enter a name for the location [$ans]: "
read ans
case "$ans" in
  "")
    ans=Location
  ;;
esac
LOCATION=$ans
echo
echo "-----------------------------------------------------------------------"
echo "Your wholist will be formatted like this:"
echo
echo "$USER $USERNAME        Flags   $LOCATION            $DOING"
echo "-----------------------------------------------------------------------"
echo
echo "Press return to continue..."
read ans
case "$ans" in
    *)
    ;;
esac
echo
ans=Chatmode
echo -n "(chatmode) Enter a name for the chatmode [$ans]: "
read ans
case "$ans" in
  "")
    ans=Chatmode
  ;;
esac
CHATMODE=$ans
ans=Chatroom
echo -n "(chatmode) Enter a name for chatrooms [$ans]: "
read ans
case "$ans" in
  "")
    ans=Chatroom
  ;;
esac
CHATROOM=$ans
echo
echo "Press return to continue..."
read ans
case "$ans" in
  *)
  ;;
esac
clear
echo
echo "PART 3 - Choosing titles."
echo "-----------------------------------------------------------------------"
echo "Now, it is time to configure titles you would like the different type"
echo "of admins to have. If you just press return they will get the standard"
echo "YAWC titles."
echo "-----------------------------------------------------------------------"
echo
echo "Press return to continue..."
read ans
case "$ans" in
    *)
    ;;
esac
echo
ans=Admin
echo -n "Enter a title for admin [$ans]: "
read ans
case "$ans" in
  "")
    ans=Admin
  ;;
esac
ADMIN=$ans
ans=Wizard
echo -n "Enter a title for wizards [$ans]: "
read ans
case "$ans" in
  "")
    ans=Wizard
  ;;
esac
WIZARD=$ans
ans=Sysop
echo -n "Enter a title for sysops [$ans]: "
read ans
case "$ans" in
  "")
    ans=Sysop
  ;;
esac
SYSOP=$ans
ans=Technician
echo -n "Enter a title for programmers [$ans]: "
read ans
case "$ans" in
  "")
    ans=Technician
  ;;
esac
PROGRAMMER=$ans
ans=Roomaide
echo -n "Enter a title for roomaides [$ans]: "
read ans
case "$ans" in
  "")
    ans=Roomaide
  ;;
esac
ROOMAIDE=$ans
ans=SysGuide
echo -n "Enter a title for guides [$ans]: "
read ans
case "$ans" in
  "")
    ans=SysGuide
  ;;
esac
GUIDE=$ans
echo
echo "Press return to continue..."
read ans
case "$ans" in
    *)
    ;;
esac
clear
echo
echo "PART 4 - Choosing colours."
echo "-----------------------------------------------------------------------"
echo "The BBS supports ANSI colours, so you can choose which colour you want"
echo "certain things to be. You can choose from the following:"
echo
echo "  1: BLUE     5: RED"
echo "  2: GREEN    6: PURPLE"
echo "  3: YELLOW   7: CYAN"
echo "  4: WHITE"
echo
echo "When prompted, just enter the corresponding number for the colour you want."
echo "-----------------------------------------------------------------------"
echo
echo "Press return to continue..."
read ans
case "$ans" in
    *)
    ;;
esac
echo
ans=4
echo -n "Enter colour for $ADMIN [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
ADMINCOL=$ans
ans=4
echo -n "Enter colour for $WIZARD [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
WIZARDCOL=$ans
ans=6
echo -n "Enter colour for $SYSOP [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
SYSOPCOL=$ans
ans=1
echo -n "Enter colour for $PROGRAMMER [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
PROGRAMMERCOL=$ans
ans=5
echo -n "Enter colour for $ROOMAIDE [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
ROOMAIDECOL=$ans
ans=7
echo -n "Enter colour for $GUIDE [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
GUIDECOL=$ans
ans=2
echo -n "Enter colour for $USER [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
USERCOL=$ans
ans=7
echo -n "Enter colour for $EXPRESS friends [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
FRIENDCOL=$ans
ans=2
echo -n "Enter colour for normal $FORUM [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
NORMAL_COL=$ans
ans=6
echo -n "Enter colour for anonymous $FORUM [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
ANON_COL=$ans
ans=5
echo -n "Enter colour for private $FORUM [$ans]: "
read ans
case "$ans" in
  "")
    ans=WHITE
    ;;
  1)
    ans=BLUE
    ;;
  2)
    ans=GREEN
    ;;
  3)
    ans=YELLOW
    ;;
  4)
    ans=WHITE
    ;;
  5)
    ans=RED
    ;;
  6)
    ans=PURPLE
    ;;
  7)
    ans=CYAN
    ;;
esac
PRIVATE_COL=$ans


echo -n "Creating $CONFIGFILE... "
echo -e "/* Mono Code BBS Setup file - Generated by setup script */" >> $CONFIGFILE
echo -e "/* $RUNNER - $DATE */" >> $CONFIGFILE
echo -e "/* \$Id\$ */" >> $CONFIGFILE
echo >> $CONFIGFILE
echo -e "/* name definitions */" >> $CONFIGFILE
echo -e "#define BBSNAME\t\t\"$BBSNAME\"\t\t/* full name of the BBS*/" >> $CONFIGFILE
echo -e "#define FORUM\t\t\"$FORUM\"\t\t/* name for a forum */" >> $CONFIGFILE
echo -e "#define MESSAGE\t\t\"$MESSAGE\"\t\t/* name for a post */" >> $CONFIGFILE
echo -e "#define EXPRESS\t\t\"$EXPRESS\"\t\t/* title for express */" >> $CONFIGFILE
echo -e "#define X_MESSAGE\t\"$X_MESSAGE\"\t\t/* name for express */" >> $CONFIGFILE
echo -e "#define USER\t\t\"$USER\"\t\t/* title for users */" >> $CONFIGFILE
echo -e "#define USERNAME\t\"$USERNAME\"\t\t/* used in the wholist header in combination with USER */" >> $CONFIGFILE
echo -e "#define DOING\t\t\"$DOING\"\t\t/* name for doing */" >> $CONFIGFILE
echo -e "#define LOCATION\t\"$LOCATION\"\t\t/* name for location in wholist */" >>$CONFIGFILE
echo -e "#define CHATMODE\t\"$CHATMODE\"\t\t/* name for chatmode */" >> $CONFIGFILE
echo -e "#define CHATROOM\t\"$CHATROOM\"\t\t/* name for chatroom */" >> $CONFIGFILE
echo >> $CONFIGFILE
echo -e "/* title definitions */" >> $CONFIGFILE
echo -e "#define ADMIN\t\t\"$ADMIN\"" >> $CONFIGFILE
echo -e "#define WIZARD\t\t\"$WIZARD\"" >> $CONFIGFILE
echo -e "#define SYSOP\t\t\"$SYSOP\"" >> $CONFIGFILE
echo -e "#define PROGRAMMER\t\t\"$PROGRAMMER\"" >> $CONFIGFILE
echo -e "#define ROOMAIDE\t\t\"$ROOMAIDE\"" >> $CONFIGFILE
echo -e "#define GUIDE\t\t\"$GUIDE\"" >> $CONFIGFILE
echo >> $CONFIGFILE
echo "/* title definitions for profiles */" >> $CONFIGFILE
echo -e "#define EXTADMINTITLE\t\tBOLD ADMINCOL \"\( \" ADMIN \" \)\"" >> $CONFIGFILE
echo -e "#define EXTWIZARDTITLE\t\tBOLD WIZARDCOL \"\( \" WIZARD \" \)\"" >> $CONFIGFILE
echo -e "#define EXTSYSOPTITLE\t\tBOLD SYSOPCOL \"\( \" SYSOP \" \)\"" >> $CONFIGFILE
echo -e "#define EXTPROGRAMMERTITLE\t\tBOLD PROGRAMMERCOL \"\( \" PROGRAMMER \" \)\"" >> $CONFIGFILE
echo -e "#define EXTROOMAIDETITLE\t\tBOLD ROOMAIDECOL \"\( \" ROOMAIDE \" \)\"" >> $CONFIGFILE
echo -e "#define EXTGUIDETITLE\t\tBOLD GUIDECOL \"\( \" GUIDE \" \)\"" >> $CONFIGFILE
echo >> $CONFIGFILE
echo "/* title definitions for titled posts  and eXpress messages */" >> $CONFIGFILE
echo -e "#define ADMINTITLE\t\tBOLD WHITE \"\(** \" ADMINCOL ADMIN WHITE \" **\)\"" >> $CONFIGFILE
echo -e "#define WIZARDTITLE\t\tBOLD WHITE \"\(*** \" WIZARDCOL WIZARD WHITE \" ***\)\"" >> $CONFIGFILE
echo -e "#define SYSOPTITLE\t\tBOLD WHITE \"\(** \" SYSOPCOL SYSOP WHITE \" **\)\"" >> $CONFIGFILE
echo -e "#define PROGRAMMERTITLE\t\tBOLD WHITE \"\(* \" PROGRAMMERCOL PROGRAMMER WHITE \" *\)\"" >> $CONFIGFILE
echo -e "#define ROOMAIDETITLE\t\tBOLD WHITE \"\(* \" ROOMAIDECOL ROOMAIDE WHITE \" *\)\"" >> $CONFIGFILE
echo -e "#define GUIDETITLE\t\tBOLD WHITE \"\( \" GUIDECOL GUIDE WHITE \" \)\"" >> $CONFIGFILE
echo >> $CONFIGFILE
echo "/* colour definitions */" >> $CONFIGFILE
echo -e "#define ADMINCOL\t\t\"$ADMINCOL\"" >> $CONFIGFILE
echo -e "#define WIZARDCOL\t\t\"$WIZARDCOL\"" >> $CONFIGFILE
echo -e "#define SYSOPCOL\t\t\"$SYSOPCOL\"" >> $CONFIGFILE
echo -e "#define PROGRAMMERCOL\t\t\"$PROGRAMMERCOL\"" >> $CONFIGFILE
echo -e "#define ROOMAIDECOL\t\t\"$ROOMAIDECOL\"" >> $CONFIGFILE
echo -e "#define GUIDECOL\t\t\"$GUIDECOL\"" >> $CONFIGFILE
echo -e "#define USERCOL\t\t\"$USERCOL\"" >> $CONFIGFILE
echo -e "#define FRIENDCOL\t\t\"$FRIENDCOL\"" >> $CONFIGFILE
echo >> $CONFIGFILE
echo "/* forum colours */" >> $CONFIGFILE
echo -e "#define NORMAL_COL\t\tGREEN\t\t/* normal forum */" >> $CONFIGFILE
echo -e "#define ANON_COL\t\tPURPLE\t\t/* anon only/option forum */" >> $CONFIGFILE
echo -e "#define PRIVATE_COL\t\tRED\t\t/* invite inly forum */" >> $CONFIGFILE
echo >> $CONFIGFILE
echo "/* colours -- don't change this */" >> $CONFIGFILE
echo -e "#define BOLD\t\t\"\\1f\"" >> $CONFIGFILE
echo -e "#define WHITE\t\t\"\\1w\"" >> $CONFIGFILE
echo -e "#define CYAN\t\t\"\\1c\"" >> $CONFIGFILE
echo -e "#define YELLOW\t\t\"\\1y\"" >> $CONFIGFILE
echo -e "#define GREEN\t\t\"\\1g\"" >> $CONFIGFILE
echo -e "#define BLUE\t\t\"\\1b\"" >> $CONFIGFILE
echo -e "#define PURPLE\t\t\"\\1p\"" >> $CONFIGFILE
echo -e "#define RED\t\t\"\\1r\"" >> $CONFIGFILE
echo -e "#define DARK\t\t\"\\1d\"" >> $CONFIGFILE
echo -e "#define NONE\t\t\"\\1a\"" >> $CONFIGFILE
echo >> $CONFIGFILE
echo "/* eof */" >> $CONFIGFILE
echo "done."
