<?php

    // Print content type first.
    //
    Header( "Content-type: image/gif" );

    // Image, font and string data passed through.
    //
    $url_array=explode("/",$REQUEST_URI);

    // First, get the font info.
    //
    $font_info = explode(",", $url_array[3]);
    $font = "/usr/bbs/www/bbs/font/". $font_info[0] .".ttf";
    $size = $font_info[1];

    // Then, get the string to display.
    //
    $text = rawurldecode($url_array[4]);

    // Now, determine the image size we need. The image we are
    // going to create will have 2 pixels border on each side.
    //
    $bounds = ImageTTFBBox( $size, 0, $font, $text );
    $width = $bounds[4] + 4;
    $height = $bounds[3] + 4;

    // Create the image and set fore and background colours.
    //
    $im = imagecreate( $width, $height );
    $black = ImageColorAllocate( $im, 0, 0, 0 );
    $white = ImageColorAllocate( $im, 255, 255, 255 );

    // Draw the string onto the image.
    //
    ImageTTFText( $im, $size, 0, 2, $height-2, $white, $font, $text );

    // Dump output :)
    //
    ImageGif( $im );

    // Destroy image.
    //
    ImageDestroy( $im );

?>
