<?php

    Header( "Content-type: image/gif" );

    // $url_array=explode("/",$REQUEST_URI);

    $font = "/usr/bbs/www/bbs/font/Arialblack_I.ttf";
    // $text = rawurldecode($url_array[3]);
    $text = "Bing!";

    $im = imagecreate( 500, 40 );
    $black = ImageColorAllocate( $im, 0, 0, 0 );
    $white = ImageColorAllocate( $im, 255, 255, 255 );
    $bounds = ImageTTFBBox( 30, 0, $font, $text );
    $x = 500 - ((500 - $bounds[2]-$bounds[0]))/2);
    $y = 30 - ((30 - ($bounds[1]-$bounds[3]))/2);
    ImageTTFText( $im, 30, 0, $x, $y, $white, $font, $text );
    ImageGif( $im );
    ImageDestroy( $im );

?>
