<?php

    // Save execution start time.
    //
    $starttime = microtime();

    // Print header; caching info etc.
    //
    echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">\n";
    echo "<html lang=\"en\">\n";
    echo "<head>\n\n";
    echo "<meta name=\"Generator\" content=\"PHP ". phpversion() ."\">\n";
    echo "<meta name=\"Process-id\" content=\"". getmypid() ."\">\n";
    echo "<meta name=\"Location\" content=\"$REQUEST_URI\">\n\n";
    echo "<meta name=\"Rcsid\" content=\"\$Id$\">\n";
    echo "<meta http-equiv=\"Expires\" content=\"" . gmdate("l, d F Y H:i:s") ." CET\">\n";
    echo "<meta http-equiv=\"Last-Modified\" content=\"" . gmdate("l, d F Y H:i:s") ." CET\">\n";
    echo "<meta http-equiv=\"Cache-Control\" content=\"no-cache, must-revalidate\">\n";
    echo "<meta http-equiv=\"Pragma\" content=\"no-cache\">\n";

    // Get username and print off proper title.
    //
    $username = getenv("REMOTE_USER");

    require('engine/html.inc');

    if( html_print_title( $username, $REQUEST_URI ) )
        html_do_login( $username );
    else
        html_do_logout( $username, getenv("REMOTE_HOST") );

    // Show stylesheet info.
    //
    echo "<style>\n";
    echo "  p  		{ font: 12pt Helvetica; }\n";
    echo "  ul  	{ font: 12pt Helvetica; }\n";
    echo "  li  	{ font: 12pt Helvetica; }\n";
    echo "  a  		{ font: 12pt Helvetica; color: #FFFF00; text-decoration: underline; }\n";
    echo "  pre		{ font: 12pt Helvetica; }\n";
    echo "  font	{ font: 12pt Helvetica; }\n";
    echo "  b		{ font-weight: bold; }\n";
    echo "  .reply	{ font: 10pt Helvetica; }\n";
    echo "  .green	{ color: #00cc00; }\n";
    echo "  .red	{ font: 10pt Times; font-weight: bold; color: #ff0000; }\n";
    echo "  .footer	{ font: 10pt Times; text-align: center; }\n";
    echo "</style>\n";

    // Header end and body start.
    //
    echo "</head>\n";
    echo "<body bgcolor=\"#000000\" text=\"#FFFFFF\">\n";

    require ("engine/routines.inc");

    // Pick url open into commands.
    //
    $url_array=explode("/",$REQUEST_URI);

    // Assign values so we can use 'em.
    $action=$url_array[3];		// What action?
    $quad=$url_array[4];		// First arg.
    $recipient=$url_array[4];		// First arg too.
    $message=$url_array[5];		// Second arg.
    $interface=$url_array[5];		// Second arg too.
    $direction=$url_array[6];		// Third arg.

    if($action != "x")
        $location = strtr($REQUEST_URI, "/", "-");
    else
        $location=$url_array[6];	// Third arg too.

    list_x_messages($username,$location);

    switch ($action) {

        case "a":	// PHP info.
            echo "<pre>\n" . phpinfo() . "</pre>\n";
            break;

        case "e":	// Enter (new).
        case "f":	// Followup (reply).
            require ('engine/post.inc');
            enter_message($username,$quad,$message,$action);
            break;

        case "l":
            require ('engine/list.inc');
            list_quads($username);
            break;

        case "m":
            require ('engine/quad.inc');
            list_messages($username,$quad);
            break;

        case "q":
            do_logout($username);
            break;

        case "r":
            require ('engine/read.inc');
            read_message($username,$quad,$message,$direction);
            break;

        case "w":
            require ('engine/who.inc');
            show_wholist($username,$location);
            break;

        case "x":
            require ('engine/express.inc');
            express_message($username,$recipient,$interface,$location);
            break;

        default:
            main_screen($username);
            break;

    }

    if( $action != "q" )
        html_print_foot($username, $starttime);
    
?>

</body>
</html>
