<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html lang="en">
<head>
<meta name="rcsid" content="$Id$">

<?php

    // Get username and print off proper title.
    //
    require('engine/html.inc');
    if( html_print_title( getenv("REMOTE_USER"), $REQUEST_URI ) )
        html_do_login( getenv("REMOTE_USER") );
    else
        html_do_logout( getenv("REMOTE_USER"), getenv("REMOTE_HOST") );

?>

<style>
  p  		{ font: 12pt Helvetica; }
  ul  		{ font: 12pt Helvetica; }
  li  		{ font: 12pt Helvetica; }
  a  		{ font: 12pt Helvetica; color: #FFFF00; text-decoration: underline; }
  pre		{ font: 12pt Helvetica; }
  font		{ font: 12pt Helvetica; }
  b		{ font-weight: bold; }
  .reply	{ font: 10pt Helvetica; }
  .green	{ color: #00cc00; }
  .red		{ font: 10pt Times; font-weight: bold; color: #ff0000; }
  .footer	{ font: 10pt Times; text-align: center; }
</style>

</head>
<body bgcolor="#000000" text="#FFFFFF">


<?php

    $starttime = microtime();

    $username = getenv("REMOTE_USER");
    require ("engine/routines.inc");

    // Pick url open into commands.
    $location=strtr($REQUEST_URI, "/", "-");
    $url_array=explode("/",$REQUEST_URI);

    // Assign values so we can use 'em.
    $action=$url_array[3];		// What action?
    $quad=$url_array[4];		// First arg.
    $recipient=$url_array[4];		// First arg too.
    $message=$url_array[5];		// Second arg.
    $interface=$url_array[5];		// Second arg too.
    $direction=$url_array[6];		// Third arg.

    list_x_messages($username,$loc);

    switch ($action) {

        case "e":	// Enter (new).
        case "f":	// Followup (reply).
            require ('engine/post.inc');
            enter_message($username,$quad,$message,$action);
            break;

        case "l":
            require ('engine/list.inc');
            list_quads($username);
            break;

        case "m":
            require ('engine/quad.inc');
            list_messages($username,$quad);
            break;

        case "q":
            do_logout($username);
            break;

        case "r":
            require ('engine/read.inc');
            read_message($username,$quad,$message,$direction);
            break;

        case "w":
            require ('engine/who.inc');
            show_wholist($username,$location);
            break;

        case "x":
            require ('engine/express.inc');
            express_message($username,$recipient,$interface,$location);
            break;

        default:
            main_screen($username);
            break;

    }

    if( $action != "q" )
        html_print_foot($username, $starttime);
    
?>

</body>
</html>
