<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html lang="en">
<head>
<meta name="rcsid" content="$Id$">

<?php

    // Get username and print off proper title.
    //
    $sender = rawurldecode($sender);
    $recipient = rawurldecode($recipient);
    $interface = rawurldecode($interface);
    $location = rawurldecode($location);
    $location = strtr($location, "-", "/");
    print "<title>$sender@Monolith BBS: Sending eXpress message to $recipient@$interface</title>\n";
    print "<meta http-equiv=\"Refresh\" content=\"5; url=http://monolith.yawc.net$location\">\n";

?>

<style>
  p  		{ font: 12pt Helvetica; }
  ul  		{ font: 12pt Helvetica; }
  li  		{ font: 12pt Helvetica; }
  a  		{ font: 12pt Helvetica; color: #FFFF00; text-decoration: underline; }
  pre		{ font: 12pt Helvetica; }
  font		{ font: 12pt Helvetica; }
  b		{ font-weight: bold; }
  .reply	{ font: 10pt Helvetica; }
  .green	{ color: #00cc00; }
  .red		{ font: 10pt Times; font-weight: bold; color: #ff0000; }
  .footer	{ font: 10pt Times; text-align: center; }
</style>

</head>
<body bgcolor="#000000" text="#FFFFFF">


<?php

    $starttime = microtime();

    require ("engine/routines.inc");

    $username = rawurldecode($sender);
    $recipient = rawurldecode($recipient);
    $u_id = get_usernum($username);
    $r_id = get_usernum($recipient);
    $interface = rawurldecode($interface);
    $message = rawurldecode($message);
    $message = htmlspecialchars($message);
    $message = strtr($message, "'", "\\'");

    list_x_messages($username, $location);

    connect_db();

    $result = MYSQL_QUERY("INSERT INTO webx (sender,recipient,message,date,status,i_sender,i_recipient) VALUES ($u_id,$r_id,'$message',NOW(),'unread','web','$interface')");
    if ($result == true )
        print "<h3 align=\"center\">eXpress message to $recipient@$interface was sucessfully saved</h3>\n";
    else {
        print "<h3 align=\"center\">eXpress message to $recipient@$interface could not be saved due to an error</h3>\n";
        echo "<h2 align=\"center\">". mysql_error() ."</h2>\n";
    }

    print "<h3 align=\"center\">You will be taken <a href=\"$location\">back</a> in 5 seconds.\n";

    require ('engine/html.inc');
    html_print_foot($username, $starttime);
    
?>

</body>
</html>
