<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html lang="en">
<head>
<meta name="rcsid" content="$Id$">

<?php

    // Get username and print off proper title.
    //
    require('engine/html.inc');
    html_print_title( getenv("REMOTE_USER"), $REQUEST_URI );

?>

<style>
  p  		{ font: 12pt Helvetica; }
  ul  		{ font: 12pt Helvetica; }
  li  		{ font: 12pt Helvetica; }
  a  		{ font: 12pt Helvetica; color: #FFFF00; text-decoration: underline; }
  pre		{ font: 12pt Helvetica; }
  font		{ font: 12pt Helvetica; }
  b		{ font-weight: bold; }
  .reply	{ font: 10pt Helvetica; }
  .green	{ color: #00cc00; }
  .red		{ font: 10pt Times; font-weight: bold; color: #ff0000; }
  .footer	{ font: 10pt Times; text-align: center; }
</style>

</head>
<body bgcolor="#000000" text="#FFFFFF">


<?php

    $starttime = microtime();

    $username = getenv("REMOTE_USER");
    require ("engine/routines.inc");

    $u_id = get_usernum($username);
    $recipient = rawurldecode($recipient);
    $r_id = $recipient;
    $recipient = get_username($r_id);
    $message = rawurldecode($message);
    $message = htmlspecialchars($message);
    $message = nl2br($message);
    $message = strtr($message, "'", "\\'");

    list_x_messages($username);

    connect_db();

    $result = MYSQL_QUERY("INSERT INTO webx (sender,recipient,message,date,status) VALUES ($u_id,$r_id,'$message',NOW(),'unread')");
    if ($result == true )
        print "<h3 align=\"center\">eXpress message to $recipient was sucessfully saved</h3>\n";
    else {
        print "<h3 align=\"center\">eXpress message to $recipient could not be saved due to an error</h3>\n";
        echo "<h2 align=\"center\">". mysql_error() ."</h2>\n";
    }

    html_print_foot($username, $starttime);
    
?>

</body>
</html>
