<html>
<head>
<title>Test</title>
</head>
<body bgcolor="#ffffff">

<?

require('engine/routines.inc');

function valid( $file_type ) {
    if($file_type == "image/gif")
        return 1;
    if($file_type == "image/jpeg")
        return 1;
    if($file_type == "image/jpg")
        return 1;
    if($file_type == "image/png")
        return 1;
    return 0;
}

connect_db();
$username = getenv("REMOTE_USER");
$usernum = get_usernum($username);

putenv("REMOTE_USER=$username");

echo "<p>$username/$usernum<br>\n";

if(
    ($userfile == null || $userfile == "") ||
    ($userfile != null && $userfile != "" && valid($userfile_type) == 0)
  )  {

    if ($userfile != null && $userfile != "")
	    echo "<h2 align=\"center\">Invalid file type: \"$userfile_type\"</h2>\n";
    echo "<p align=\"center\">Accepted types: GIF, JPEG and PNG.<br>\n";
    echo "<form enctype=\"multipart/form-data\" action=\"/bbs/test.phtml\" method=\"post\"\n";
    echo "  <input type=\"hidden\" name=\"MAX_FILE_SIZE\" value=\"10000\">\n";
    echo "  <input type=\"hidden\" name=\"USER_ID\" value=\"$usernum\">\n";
    echo "  Send this file: <input name=\"userfile\" type=\"file\">\n";
    echo "  <input type=\"submit\" value=\"Upload File\">\n";
    echo "</form>\n";
} else {
    echo "File: `$userfile' ($userfile_type - ".filesize($userfile)." bytes)\n";
    if (file_exists($userfile)) {
	$fp = fopen($userfile, "r");
	$contents = fread($fp, filesize($userfile));
	fclose($fp);
	unlink($userfile);
	$contents = rawurlencode($contents);
	$result = mysql_query("UPDATE user SET picture='$contents' WHERE id=$USER_ID");
	$result = mysql_query("UPDATE user SET content_type='$userfile_type' WHERE id=$USER_ID");
    }
    echo "<p>Hopefully saved your file \"$userfile_name\" ($userfile_size bytes) into the database.\n";

    $result = mysql_query("SELECT content_type FROM user WHERE id=$USER_ID");
    $number = MYSQL_NUMROWS($result);
    if ($number) {
	$content_type = mysql_result($result, 0, "content_type");
	if ($content_type == "image/gif")
	    echo "<img src=\"/bbs/pix/gif.php3?$USER_ID\" width=\"100\">\n";
	else if ($content_type == "image/jpeg")
	    echo "<img src=\"/bbs/pix/jpeg.php3?$USER_ID\" width=\"100\">\n";
	else if ($content_type == "image/png")
	    echo "<img src=\"/bbs/pix/png.php3?$USER_ID\" width=\"100\">\n";
	else
	    echo "<p>Image is in unsupported format. Use GIF, JPEG or PNG.\n";
    } else {
	echo "<p>No image\n";
    }

}



?>

</body>
</html>
